set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN T16 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN U17 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN V15 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN W15 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN U18 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN U19 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN N18 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN P19 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN N20 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN P20 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN T20 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN U20 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN V20 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN W20 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN Y18 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN Y19 [get_ports {LCD_DATA[15]}]
set_property PACKAGE_PIN P15 [get_ports I2C0_SDA]
set_property PACKAGE_PIN P16 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SDA]
set_property PACKAGE_PIN N17 [get_ports MEMS_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports MEMS_INTn]
set_property PACKAGE_PIN V16 [get_ports LCD_VSYNC]
set_property PACKAGE_PIN W16 [get_ports LCD_HSYNC]
set_property PACKAGE_PIN R16 [get_ports LCD_DE]
set_property PACKAGE_PIN R17 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DE]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_INTn]
set_property PACKAGE_PIN W19 [get_ports HDMI_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_FSYNC_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DOUT]
set_property PACKAGE_PIN V17 [get_ports I2S_DOUT]
set_property PACKAGE_PIN T17 [get_ports I2S_SCLK]
set_property PACKAGE_PIN R18 [get_ports I2S_FSYNC_OUT]
set_property PACKAGE_PIN Y16 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN Y17 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN R14 [get_ports {LEDS[2]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_output_delay -clock [get_clocks -of_objects [get_pins psd/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]] 3.000 [get_ports -filter { NAME =~  "*LCD_*" && DIRECTION == "OUT" }]

set_clock_groups -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks -of_objects [get_pins psd/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]]

set_property BITSTREAM.GENERAL.COMPRESS True [current_design]
